<p>
	<fb:like 
    	ref="under_price" 
        href="{$smarty.server.HTTP_HOST}{$smarty.server.REQUEST_URI}" 
        action="{$action}" 
        show_faces="{$faces}"
        send="{$send}"
        width="{$width}"
        height="23" 
        font="Arial">
     </fb:like>
</p>